# hypridle.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hypridle

general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend (lid close).
    after_sleep_cmd = hyprctl dispatch dpms on  # turn display back on after wake.
}

# Lock after 10 min on AC only
listener {
    timeout = 600
    on-timeout = /home/lucas/.scripts/power-profile.sh lock-if-ac
}

# Turn off display after 10 min on battery only
listener {
    timeout = 605
    on-timeout = /home/lucas/.scripts/power-profile.sh dpms-off-if-battery
    on-resume = /home/lucas/.scripts/power-profile.sh dpms-on
}

# Suspend after 30 min on battery only
listener {
    timeout = 1800
    on-timeout = /home/lucas/.scripts/power-profile.sh suspend-if-battery
}

# Turn off display after 1 hour on AC only
listener {
    timeout = 3605
    on-timeout = /home/lucas/.scripts/power-profile.sh dpms-off-if-ac
    on-resume = /home/lucas/.scripts/power-profile.sh dpms-on
}
